#!/usr/bin/env node
// Token tooling for the design review flow.
//
//   yarn design:tokens            regenerate design/tokens/current.css from packages/theme/lib/tokens.ts
//   yarn design:check             is current.css fresh, does the SCSS mirror match tokens.ts,
//                                 and do current + every proposal pass the contrast checks
//   yarn design:diff <proposal>   which tokens.ts values the proposal changes, and which tokens it adds

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { runChecks } from '../shared/contrast.mjs';

const design = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(design, '..');
const tokensTs = join(repo, 'packages/theme/lib/tokens.ts');
const variablesScss = join(repo, 'packages/app/src/theme/scss/common/variables.scss');
const currentCss = join(design, 'tokens/current.css');
const appCss = join(design, 'shared/app.css');

const GROUPS = ['surface', 'fill', 'border', 'text', 'accent', 'status', 'radius', 'shadow', 'font', 'kbd', 'traffic', 'transition', 'motion', 'glass', 'layout'];

const kebab = s => s.replace(/[A-Z]/g, c => '-' + c.toLowerCase());
const cssValue = v => (typeof v === 'number' ? `${v}px` : String(v));

/**
 * Entries in tokens.ts that point at another token (`background: fill.active`)
 * become var() references, so a proposal that changes fill.active also changes
 * the kbd chip, exactly like the code does.
 */
async function readReferences() {
  const source = await readFile(tokensTs, 'utf8');
  const refs = new Map();
  for (const group of GROUPS) {
    const block = source.match(new RegExp(`export const ${group} = \\{([\\s\\S]*?)\\n\\};`));
    if (!block) continue;
    for (const m of block[1].matchAll(new RegExp(`^\\s*(\\w+):\\s*(${GROUPS.join('|')})\\.(\\w+),?\\s*$`, 'gm'))) {
      refs.set(`${group}.${m[1]}`, `var(--${m[2]}-${kebab(m[3])})`);
    }
  }
  return refs;
}

/** tokens.ts → [{ name: '--surface-base', path: 'surface.base', value: '#1B1A19', css: '#1B1A19' }, …] */
async function readCodeTokens() {
  const mod = await import(pathToFileURL(tokensTs).href);
  const refs = await readReferences();
  const out = [];
  for (const group of GROUPS) {
    for (const [key, value] of Object.entries(mod[group])) {
      if (Array.isArray(value)) {
        value.forEach((v, i) => out.push({ name: `--${group}-${kebab(key)}-${i + 1}`, path: `${group}.${key}[${i}]`, value: cssValue(v), css: cssValue(v) }));
      } else {
        const path = `${group}.${key}`;
        out.push({ name: `--${group}-${kebab(key)}`, path, value: cssValue(value), css: refs.get(path) || cssValue(value) });
      }
    }
  }
  return out;
}

function renderCurrentCss(tokens) {
  const lines = [
    '/* GENERATED by `yarn design:tokens` from packages/theme/lib/tokens.ts. Do not edit.',
    ' * Proposals override these in design/proposals/<name>/tokens.css. */',
    ':root {',
  ];
  let group = null;
  for (const t of tokens) {
    const g = t.path.split('.')[0];
    if (g !== group) {
      if (group) lines.push('');
      lines.push(`  /* ${g} */`);
      group = g;
    }
    lines.push(`  ${t.name}: ${t.css};`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

const stripComments = css => css.replace(/\/\*[\s\S]*?\*\//g, '');

/** Custom properties set on :root by a CSS file and everything it @imports, in cascade order. */
async function collectVars(file, into = new Map()) {
  let css;
  try {
    css = stripComments(await readFile(file, 'utf8'));
  } catch {
    return into;
  }
  for (const m of css.matchAll(/@import\s+(?:url\()?["']([^"']+)["']\)?\s*;/g)) {
    await collectVars(resolve(dirname(file), m[1]), into);
  }
  for (const block of css.matchAll(/:root\s*\{([^}]*)\}/g)) {
    for (const decl of block[1].split(';')) {
      const m = decl.match(/^\s*(--[\w-]+)\s*:\s*([\s\S]+?)\s*$/);
      if (m) into.set(m[1], m[2]);
    }
  }
  return into;
}

/** Resolve var(--x, fallback) references inside token values. */
function resolver(vars) {
  const get = (name, depth = 0) => {
    const raw = vars.get(name);
    if (raw === undefined || depth > 20) return undefined;
    return raw.replace(/var\(\s*(--[\w-]+)\s*(?:,\s*([^)]*))?\)/g, (_, ref, fallback) => get(ref, depth + 1) ?? fallback ?? '');
  };
  return get;
}

async function readProposals() {
  return JSON.parse(await readFile(join(design, 'manifest.json'), 'utf8')).proposals;
}

// The stylesheets every proposal folder has, in the order the screens load them.
const PROPOSAL_FILES = ['fonts.css', 'tokens.css', 'components.css', 'tweaks.css'];

async function proposalVars(proposal, into = new Map()) {
  for (const file of PROPOSAL_FILES) await collectVars(join(design, 'proposals', proposal, file), into);
  return into;
}

async function varsFor(proposal) {
  const vars = await collectVars(currentCss);
  await collectVars(appCss, vars);
  if (proposal) await proposalVars(proposal, vars);
  return vars;
}

const norm = v => v.toLowerCase().replace(/\s+/g, ' ').replace(/\s*,\s*/g, ', ').replace(/\(\s*/g, '(').replace(/\s*\)/g, ')').trim();

// SCSS names that don't follow `$<group>-<key>` → the token they mirror.
const SCSS_ALIASES = {
  scrim: '--surface-scrim',
  accent: '--accent-default',
  success: '--status-success',
  warning: '--status-warning',
  danger: '--status-danger',
  info: '--status-info',
  badge: '--status-badge',
  'border-radius': '--radius-md',
  'border-radius-lg': '--radius-lg',
  'border-radius-xl': '--radius-xl',
};

async function checkScss(tokens) {
  const byName = new Map(tokens.map(t => [t.name, t]));
  const scss = await readFile(variablesScss, 'utf8');
  const problems = [];
  let compared = 0;
  for (const line of scss.split('\n')) {
    const m = line.replace(/\/\/.*$/, '').match(/^\s*\$([\w-]+)\s*:\s*(.+?)\s*;/);
    if (!m || m[2].startsWith('$')) continue;
    const token = byName.get(SCSS_ALIASES[m[1]] || `--${m[1]}`);
    if (!token) continue;
    compared++;
    if (norm(m[2]) !== norm(token.value)) problems.push(`$${m[1]} is ${m[2]}, but ${token.path} is ${token.value}`);
  }
  return { compared, problems };
}

function printChecks(label, results) {
  const failed = results.filter(r => r.pass === false);
  console.log(`\n${label}: ${results.filter(r => r.pass).length} pass, ${failed.length} fail, ${results.filter(r => r.skipped).length} skipped`);
  for (const r of results) {
    const mark = r.skipped ? '  –' : r.pass ? '  ✓' : '  ✗';
    const value = r.skipped ? 'n/a ' : r.value.toFixed(2).padStart(5);
    console.log(`${mark} ${value} ≥ ${r.min}  ${r.fg} on ${r.bg}  (${r.what})`);
  }
  return failed.length;
}

async function generate() {
  const css = renderCurrentCss(await readCodeTokens());
  await writeFile(currentCss, css);
  console.log(`Wrote ${relative(repo, currentCss)}`);
}

async function check() {
  let failures = 0;
  const tokens = await readCodeTokens();

  const fresh = renderCurrentCss(tokens);
  const onDisk = await readFile(currentCss, 'utf8').catch(() => '');
  if (fresh === onDisk) {
    console.log('✓ design/tokens/current.css matches tokens.ts');
  } else {
    console.log('✗ design/tokens/current.css is stale: run `yarn design:tokens`');
    failures++;
  }

  const scss = await checkScss(tokens);
  if (scss.problems.length) {
    console.log(`✗ variables.scss drifted from tokens.ts:\n  ${scss.problems.join('\n  ')}`);
    failures += scss.problems.length;
  } else {
    console.log(`✓ variables.scss mirrors tokens.ts (${scss.compared} values compared)`);
  }

  // What already ships is reported but doesn't block; proposals must pass.
  const known = printChecks('Contrast · current (shipped, warnings only)', runChecks(resolver(await varsFor(null))));
  for (const p of await readProposals()) {
    if (p.status === 'shipped') continue;
    failures += printChecks(`Contrast · ${p.id}`, runChecks(resolver(await varsFor(p.id))));
  }

  if (known) console.log(`\n${known} known contrast issue(s) in the shipped tokens (warnings).`);
  console.log(failures ? `\n${failures} problem(s).` : '\nAll checks pass.');
  process.exitCode = failures ? 1 : 0;
}

async function diff(proposal) {
  if (!proposal) throw new Error('usage: yarn design:diff <proposal>');
  const tokens = await readCodeTokens();
  const base = resolver(await varsFor(null));
  const next = resolver(await varsFor(proposal));
  const own = await proposalVars(proposal);

  console.log(`\n${proposal} → packages/theme/lib/tokens.ts (and the SCSS mirror)\n`);
  let changed = 0;
  for (const t of tokens) {
    // Only what the proposal sets itself; references (kbd.background → fill.active) follow along in code too.
    if (!own.has(t.name)) continue;
    const after = next(t.name);
    if (after !== undefined && norm(after) !== norm(base(t.name))) {
      console.log(`  ${t.path.padEnd(24)} ${base(t.name)}  →  ${after}`);
      changed++;
    }
  }
  if (!changed) console.log('  (no changes to existing tokens)');

  const known = new Set(tokens.map(t => t.name));
  const added = [...own.keys()].filter(name => !known.has(name));
  if (added.length) {
    console.log('\nNew tokens (add to tokens.ts or keep local to a component):\n');
    for (const name of added) console.log(`  ${name.padEnd(26)} ${next(name)}`);
  }

  const components = stripComments(await readFile(join(design, 'proposals', proposal, 'components.css'), 'utf8').catch(() => ''));
  const rules = (components.match(/\{/g) || []).length;
  if (rules) console.log(`\ncomponents.css has ${rules} rule(s) with structural changes; port them by hand (see notes.md).`);
  console.log('');
}

const [command = 'generate', arg] = process.argv.slice(2);
const commands = { generate, check, diff: () => diff(arg) };
if (!commands[command]) {
  console.error('usage: tokens.mjs [generate|check|diff <proposal>]');
  process.exit(2);
}
await commands[command]();
